services:
  weblate:
    ports:
      - '{{ weblate_host_port }}:8080'
    environment:
      # Admin
      WEBLATE_ADMIN_EMAIL: '{{ weblate_admin_email }}'
      WEBLATE_ADMIN_NAME: '{{ weblate_admin_name }}'
      WEBLATE_ADMIN_NOTIFY_ERROR: 0

      # Email: completely disabled
      WEBLATE_EMAIL_BACKEND: django.core.mail.backends.dummy.EmailBackend
      WEBLATE_EMAIL_HOST: 'localhost'
      WEBLATE_EMAIL_HOST_USER: 'user'
      WEBLATE_EMAIL_HOST_PASSWORD: 'pass'
      WEBLATE_SERVER_EMAIL: 'admin@example.com'
      WEBLATE_DEFAULT_FROM_EMAIL: 'admin@example.com'

      # Generic
      WEBLATE_SITE_DOMAIN: '{{ weblate_site_domain }}'
      WEBLATE_SITE_TITLE: Spyglass Localization

      # Disable backup check, as it is done through restic
      WEBLATE_SILENCED_SYSTEM_CHECKS: 'weblate.I028'

      # Sentry
      SENTRY_DSN: '{{ weblate_sentry_dsn }}'

      # GPG
      WEBLATE_GPG_IDENTITY: '{{ weblate_default_commiter_name }} <{{ weblate_default_commiter_email }}>'

      # Git
      WEBLATE_DEFAULT_COMMITER_EMAIL: '{{ weblate_default_commiter_email }}'
      WEBLATE_DEFAULT_COMMITER_NAME: '{{ weblate_default_commiter_name }}'

      # HTTPS & reverse proxy
      WEBLATE_ENABLE_HTTPS: 1
      WEBLATE_IP_PROXY_HEADER: HTTP_X_FORWARDED_FOR
      WEBLATE_SECURE_PROXY_SSL_HEADER: HTTP_X_FORWARDED_PROTO,https

      # Registration: only allows GitHub
      WEBLATE_REGISTRATION_ALLOW_BACKENDS: github
      WEBLATE_SOCIAL_AUTH_GITHUB_KEY: '{{ weblate_social_auth_github_key }}'
      WEBLATE_SOCIAL_AUTH_GITHUB_SECRET: '{{ weblate_social_auth_github_secret }}'
